# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=default_macos-arm64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),default_macos-arm64)
  STR_config = default_macos-arm64

else ifeq ($(config),default_linux-x86_64)
  STR_config = default_linux-x86_64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := STR

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

STR:
ifneq (,$(STR_config))
	@echo "==== Building STR ($(STR_config)) ===="
	@${MAKE} --no-print-directory -C src -f Makefile config=$(STR_config)
endif

clean:
	@${MAKE} --no-print-directory -C src -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  default_macos-arm64"
	@echo "  default_linux-x86_64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   STR"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"